/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AllSkyCalibrationFrame.java
 *
 * Created on Apr 26, 2012, 9:52:57 PM
 */

package edu.caltech.palomar.telescopes.P200.gui.allsky;
import edu.caltech.palomar.telescopes.P200.gui.allsky.AllSkyImageProcessor;
import javax.swing.SpinnerNumberModel;
/**
 *
 * @author developer
 */
public class AllSkyCalibrationFrame extends javax.swing.JFrame {
    public AllSkyImageProcessor myAllSkyImageProcessor;
    public SpinnerNumberModel dXSpinnerModel;
    public SpinnerNumberModel dYSpinnerModel;
    /** Creates new form AllSkyCalibrationFrame */
    public AllSkyCalibrationFrame() {
        initComponents();
        initializeSpinners();
        this.setVisible(true);
    }
public void setAllSkyImageProcessor(AllSkyImageProcessor newAllSkyImageProcessor){
    myAllSkyImageProcessor = newAllSkyImageProcessor;
}
/*================================================================================================
/     initializeSpinners()
/=================================================================================================*/
 private void initializeSpinners(){
    dXSpinnerModel    =  new SpinnerNumberModel(0,-100,100,1);
    dYSpinnerModel    =  new SpinnerNumberModel(0,-100,100,1);
    dXspinner.setModel(   dXSpinnerModel);
    dYspinner.setModel(   dYSpinnerModel);
 }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        slopeTextField = new javax.swing.JTextField();
        rotationTextField = new javax.swing.JTextField();
        dXspinner = new javax.swing.JSpinner();
        dYspinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("All Sky Image Calibration");

        jLabel2.setText("slope");

        jLabel3.setText("rotation");

        jLabel4.setText("dX");

        jLabel5.setText("dY");

        slopeTextField.setText(" ");
        slopeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slopeTextFieldActionPerformed(evt);
            }
        });

        rotationTextField.setText(" ");
        rotationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotationTextFieldActionPerformed(evt);
            }
        });

        dXspinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dXspinnerStateChanged(evt);
            }
        });

        dYspinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dYspinnerStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dXspinner, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addComponent(dYspinner, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addComponent(rotationTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(26, 26, 26)
                            .addComponent(slopeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(slopeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rotationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dXspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dYspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dYspinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dYspinnerStateChanged
       int currentValue = ((Integer)dYspinner.getValue()).intValue();
       myAllSkyImageProcessor.setDY(currentValue);
       myAllSkyImageProcessor.constructOverlay();
       myAllSkyImageProcessor.getSkyDisplay().repaint();
       // TODO add your handling code here:
    }//GEN-LAST:event_dYspinnerStateChanged

    private void dXspinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dXspinnerStateChanged
       int currentValue = ((Integer)dXspinner.getValue()).intValue();
       myAllSkyImageProcessor.setDX(currentValue);
       myAllSkyImageProcessor.constructOverlay();
       myAllSkyImageProcessor.getSkyDisplay().repaint();
    }//GEN-LAST:event_dXspinnerStateChanged

    private void rotationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotationTextFieldActionPerformed
        // TODO add your handling code here:
        java.lang.String currentText = rotationTextField.getText();
        try{
           double currentValue = Double.parseDouble(currentText);
           myAllSkyImageProcessor.setRotation(currentValue);
           myAllSkyImageProcessor.constructOverlay();
           myAllSkyImageProcessor.getSkyDisplay().repaint();
        }catch(Exception e){
           System.out.println("Error parsing number - Rotation Text Field");
        }
    }//GEN-LAST:event_rotationTextFieldActionPerformed

    private void slopeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slopeTextFieldActionPerformed
         java.lang.String currentText = slopeTextField.getText();
        try{
           int currentValue = Integer.parseInt(currentText);
           myAllSkyImageProcessor.setSlope(currentValue);
           myAllSkyImageProcessor.constructOverlay();
           myAllSkyImageProcessor.getSkyDisplay().repaint();
        }catch(Exception e){
           System.out.println("Error parsing number - Rotation Text Field");
        }
       // TODO add your handling code here:
    }//GEN-LAST:event_slopeTextFieldActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllSkyCalibrationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner dXspinner;
    private javax.swing.JSpinner dYspinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField rotationTextField;
    private javax.swing.JTextField slopeTextField;
    // End of variables declaration//GEN-END:variables

}
