/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  developer
 * Created: Aug 21, 2019
 */
CREATE TABLE `telemetry`.`p200telemetry` (
  `AIRMASS` FLOAT NULL COMMENT 'This table contains the telemetry information for the P200 telescope including the ephemeris information calculated using JSKYCALC',
  `AZIMUTH` FLOAT NULL,
  `CASSANG` FLOAT NULL,
  `DATE` DATE NULL,
  `DEC` VARCHAR(45) NOT NULL,
  `DECOFF` FLOAT NULL,
  `DECTRAC` FLOAT NULL,
  `DOMEAZI` FLOAT NULL,
  `DOMESHU` VARCHAR(45) NULL,
  `EQUINOX` FLOAT NULL,
  `HA` VARCHAR(45) NULL,
  `INSTRMNT` VARCHAR(45) NULL,
  `LST` VARCHAR(45) NULL,
  `OBJECT` VARCHAR(45) NULL,
  `PUMPS` VARCHAR(45) NULL,
  `RA` VARCHAR(45) NOT NULL,
  `RAOFF` FLOAT NULL,
  `RATEDEC` FLOAT NULL,
  `RATERA` FLOAT NULL,
  `TELFOCUS` FLOAT NULL,
  `TELID` VARCHAR(45) NULL,
  `TMOTION` VARCHAR(45) NULL,
  `UTCSTART` DATETIME NOT NULL,
  `WINDSCR` VARCHAR(45) NULL,
  `ZA` FLOAT NULL,
  `ALTITUDE` FLOAT NULL,
  `BARYJD` DOUBLE NULL,
  `BARYVCOR` VARCHAR(45) NULL,
  `CONSTEL` VARCHAR(45) NULL,
  `ELEVHOR` VARCHAR(45) NULL,
  `ELEVSEA` VARCHAR(45) NULL,
  `JD` DOUBLE NULL,
  `LAT` VARCHAR(45) NULL,
  `LONG` VARCHAR(45) NULL,
  `MOONALT` FLOAT NULL,
  `MOONANG` FLOAT NULL,
  `MOONAZ` FLOAT NULL,
  `MOONDEC` VARCHAR(45) NULL,
  `MOONLIG` VARCHAR(45) NULL,
  `MOONILM` VARCHAR(45) NULL,
  `MOONPH` VARCHAR(45) NULL,
  `MOONRA` VARCHAR(45) NULL,
  `PARA` FLOAT NULL,
  `PLANETW` VARCHAR(45) NULL,
  `SUNALT` FLOAT NULL,
  `SUNAZ` FLOAT NULL,
  `SUNDEC` VARCHAR(45) NULL,
  `SUNRA` VARCHAR(45) NULL,
  `ZTWILIGH` VARCHAR(45) NULL,
  PRIMARY KEY (`UTCSTART`));

