CREATE TABLE `acamd` (
  `datetime` datetime(3) NOT NULL COMMENT 'YYYY-MM-DD hh:mm:ss.sss',
  `name` varchar(128) DEFAULT NULL COMMENT 'Target name',
  `obs_id` int DEFAULT NULL COMMENT 'observation ID',
  `RA` varchar(32) DEFAULT NULL COMMENT 'Target RA (hh:mm:ss.s)',
  `DECL` varchar(32) DEFAULT NULL COMMENT 'Target DEC (dd:mm:ss.s)',
  `RAtel` varchar(32) DEFAULT NULL COMMENT 'TCS RA (hh:mm:ss.s)',
  `DECLtel` varchar(32) DEFAULT NULL COMMENT 'TCS DEC (dd:mm:ss.s)',
  `airmass` float DEFAULT NULL COMMENT 'TCS airmass',
  `az` float DEFAULT NULL COMMENT 'TCS azimuth',
  `casangle` float DEFAULT NULL COMMENT 'TCS Cassegrain ring angle',
  `filter` varchar(16) DEFAULT NULL COMMENT 'Filter selection on ACAM',
  `pointmode` varchar(8) DEFAULT NULL COMMENT 'Pointing target at slit or ACAM',
  `focus` float DEFAULT NULL COMMENT 'TCS focus position',
  `RAoffset` float DEFAULT NULL COMMENT 'PT input (arcsec)',
  `DECLoffset` float DEFAULT NULL COMMENT 'PT input (arcsec)',
  `acquired` tinyint DEFAULT NULL COMMENT 'TRUE means ACAM is in guiding mode after acquiring target',
  `flags` varchar(32) DEFAULT NULL,
  `RAsolve` float DEFAULT NULL COMMENT 'Astrometry solution for ACAM center (deg)',
  `DECsolve` float DEFAULT NULL COMMENT 'Astrometry solution for ACAM center (deg)',
  `ANGsolve` float DEFAULT NULL COMMENT 'Astrometry solution for ACAM position angle (deg)',
  `rms_arcsec` float DEFAULT NULL COMMENT 'RMS residuals of solver WCS fit (arcsec)',
  `result` varchar(8) DEFAULT NULL COMMENT 'Result of astrometry solver (GOOD, NOISY, etc.)',
  `matches` int DEFAULT NULL COMMENT 'Number of matches sources from solver',
  `seeing` float DEFAULT NULL COMMENT 'median seeing in ACAM field (arcsec)',
  `seeing_zen` float DEFAULT NULL COMMENT 'seeing extrapolated to zenith (arcsec)',
  `seeing_std` float DEFAULT NULL COMMENT 'STDDEV seeing in ACAM field (arcsec)',
  `background` float DEFAULT NULL COMMENT 'median background in ACAM field (mag/argsec^2)',
  `background_std` float DEFAULT NULL COMMENT 'STDDEV background in ACAM field (mag/argsec^2)',
  `extinction` float DEFAULT NULL COMMENT 'median extinction in ACAM field (mag/argsec^2)',
  `extinction_std` float DEFAULT NULL COMMENT 'STDDEV extinction in ACAM field (mag/argsec^2)',
  PRIMARY KEY (`datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
