CREATE TABLE `focusd` (
  `datetime` varchar(23) NOT NULL,
  `T_U` decimal(8,3) DEFAULT NULL COMMENT 'Structure temperature (K)',
  `T_G` decimal(8,3) DEFAULT NULL COMMENT 'Structure temperature (K)',
  `T_R` decimal(8,3) DEFAULT NULL COMMENT 'Structure temperature (K)',
  `T_I` decimal(8,3) DEFAULT NULL COMMENT 'Structure temperature (K)',
  `T_air` decimal(8,3) DEFAULT NULL COMMENT 'Air temperature (K)',
  `ShiftFocus_U` decimal(8,3) DEFAULT NULL COMMENT 'Predicted shift in focus position (µm)',
  `ShiftFocus_G` decimal(8,3) DEFAULT NULL COMMENT 'Predicted shift in focus position (µm)',
  `ShiftFocus_R` decimal(8,3) DEFAULT NULL COMMENT 'Predicted shift in focus position (µm)',
  `ShiftFocus_I` decimal(8,3) DEFAULT NULL COMMENT 'Predicted shift in focus position (µm)',
  `Offset_U` decimal(8,3) DEFAULT NULL COMMENT 'Focus motor offset from reference position (µm)',
  `Offset_G` decimal(8,3) DEFAULT NULL COMMENT 'Focus motor offset from reference position (µm)',
  `Offset_R` decimal(8,3) DEFAULT NULL COMMENT 'Focus motor offset from reference position (µm)',
  `Offset_I` decimal(8,3) DEFAULT NULL COMMENT 'Focus motor offset from reference position (µm)',
  `T0_U` decimal(8,3) DEFAULT NULL COMMENT '(CONSTANT) reference temperature (K)',
  `T0_G` decimal(8,3) DEFAULT NULL COMMENT '(CONSTANT) reference temperature (K)',
  `T0_R` decimal(8,3) DEFAULT NULL COMMENT '(CONSTANT) reference temperature (K)',
  `T0_I` decimal(8,3) DEFAULT NULL COMMENT '(CONSTANT) reference temperature (K)',
  `MotorPos_U` decimal(8,3) DEFAULT NULL COMMENT '(CONSTANT) Motor position at T0 (µm)',
  `MotorPos_G` decimal(8,3) DEFAULT NULL COMMENT '(CONSTANT) Motor position at T0 (µm)',
  `MotorPos_R` decimal(8,3) DEFAULT NULL COMMENT '(CONSTANT) Motor position at T0 (µm)',
  `MotorPos_I` decimal(8,3) DEFAULT NULL COMMENT '(CONSTANT) Motor position at T0 (µm)',
  PRIMARY KEY (`datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
