CREATE TABLE `thermald` (
  `datetime` datetime(3) NOT NULL,
  `TCCD_U` float DEFAULT NULL COMMENT 'CCD temperature (K)',
  `TCCD_G` float DEFAULT NULL COMMENT 'CCD temperature (K)',
  `TCCD_R` float DEFAULT NULL COMMENT 'CCD temperature (K)',
  `TCCD_I` float DEFAULT NULL COMMENT 'CCD temperature (K)',
  `Tdewar_U` float DEFAULT NULL COMMENT 'dewar temperature (K)',
  `Tdewar_G` float DEFAULT NULL COMMENT 'dewar temperature (K)',
  `Tdewar_R` float DEFAULT NULL COMMENT 'dewar temperature (K)',
  `Tdewar_I` float DEFAULT NULL COMMENT 'dewar temperature (K)',
  `heat_U` float DEFAULT NULL COMMENT 'CCD heater power (%)',
  `heat_G` float DEFAULT NULL COMMENT 'CCD heater power (%)',
  `heat_R` float DEFAULT NULL COMMENT 'CCD heater power (%)',
  `heat_I` float DEFAULT NULL COMMENT 'CCD heater power (%)',
  `TCOLL_U` float DEFAULT NULL COMMENT 'collimator temp (C)',
  `TCOLL_G` float DEFAULT NULL COMMENT 'collimator temp (C)',
  `TCOLL_R` float DEFAULT NULL COMMENT 'collimator temp (C)',
  `TCOLL_I` float DEFAULT NULL COMMENT 'collimator temp (C)',
  `TFOCUS_U` float DEFAULT NULL COMMENT 'focus stage air temp (C)',
  `TFOCUS_G` float DEFAULT NULL COMMENT 'focus stage air temp (C)',
  `TFOCUS_R` float DEFAULT NULL COMMENT 'focus stage air temp (C)',
  `TFOCUS_I` float DEFAULT NULL COMMENT 'focus stage air temp (C)',
  `TRACKSURF` float DEFAULT NULL COMMENT 'rack surface temp (C)',
  `TRACK_1` float DEFAULT NULL COMMENT 'rack temp 1 (C)',
  `TRACK_2` float DEFAULT NULL COMMENT 'rack temp 2 (C)',
  `TRACK_3` float DEFAULT NULL COMMENT 'rack temp 3 (C)',
  `TFLEXCON_IG` float DEFAULT NULL COMMENT 'Flexure TTP controller rack temp (C)',
  `TFLEXCON_UR` float DEFAULT NULL COMMENT 'Flexure TTP controller rack temp (C)',
  `TRHRACK_1` float DEFAULT NULL COMMENT 'rack temp from humidity sensor 1 (C)',
  `TRHRACK_2` float DEFAULT NULL COMMENT 'rack temp from humidity sensor 2 (C)',
  `RHRACK_1` float DEFAULT NULL COMMENT 'rack relative humidity 1 (%)',
  `RHRACK_2` float DEFAULT NULL COMMENT 'rack relative humidity 2 (%)',
  `RHETA_B` float DEFAULT NULL COMMENT 'Etalon blue relative humidity (%)',
  `RHETA_R` float DEFAULT NULL COMMENT 'Etalon red relative humidity (%)',
  `TETA_B` float DEFAULT NULL COMMENT 'Etalon temp blue (C)',
  `TETA_R` float DEFAULT NULL COMMENT 'Etalon temp red (C)',
  `TACAM` float DEFAULT NULL COMMENT 'ACAM structure internal temp (C)',
  `TANDOR_ACAM` float DEFAULT NULL COMMENT 'Andor temp; ACAM (C)',
  `TANDOR_SCAM_L` float DEFAULT NULL COMMENT 'Andor temp; slicer cam L (C)',
  `TANDOR_SCAM_R` float DEFAULT NULL COMMENT 'Andor temp; slicer cam R (C)',
  PRIMARY KEY (`datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
