#!/bin/bash

# Once you CLEAN and BUILD the development version of the GUI, 
# run this script to copy the development version of the GUI in this directory
# to the public deployment directory and then rsync with the main ngps computer

synclist=DEPLOY.TXT
dest=/usr/local/palomar/deployment/NGPS_GUI/

read -p "Do you wish to deploy to $dest ? [y/N]:  " yn
case $yn in
    [Yy]* ) 
	echo ''
	echo 'SYNCING EXTERNAL FILES AND FOLDERS'
	rsync -arv . $dest --files-from=$synclist

	echo ''
	echo 'SYNCING JAR FILE AND LIB'
	rsync -arv ./dist/ $dest
	;;
    * ) echo "Canceled"; exit;;
esac

echo ""
echo ""

# Copy to deployment machine
rsync -avz /usr/local/palomar/deployment/NGPS_GUI developer@ngps.caltech.edu:/usr/local/palomar/deployment

