#!/bin/bash

dest=/usr/local/palomar/deployment/NGPS_GUI/

echo ''
echo 'SYNCING EXTERNAL FILES AND FOLDERS'
rsync -arv . $dest --files-from=DEPLOY.TXT

echo ''
echo 'SYNCING JAR FILE AND LIB'
rsync -arv ./dist/ $dest
