CREATE TABLE `completed_obs` (
  `LOG_ID` int NOT NULL AUTO_INCREMENT,
  `OWNER` varchar(32) NOT NULL COMMENT 'Name of target list owner',
  `OBSERVATION_ID` int DEFAULT NULL COMMENT 'ID from the master targets table',
  `SET_ID` int DEFAULT NULL COMMENT 'ID of the user''s target set',
  `TARGET_NUMBER` int DEFAULT NULL,
  `SEQUENCE_NUMBER` int DEFAULT NULL,
  `NAME` varchar(128) NOT NULL COMMENT 'Name of the astronomical target or calibration',
  `FITSFILE` varchar(512) DEFAULT NULL COMMENT 'File with the spectrum images',
  `RA` varchar(32) DEFAULT NULL COMMENT 'Target Right Ascension',
  `DECL` varchar(32) DEFAULT NULL COMMENT 'Target Declination',
  `TELRA` varchar(32) DEFAULT NULL COMMENT 'Telescope RA',
  `TELDECL` varchar(32) DEFAULT NULL COMMENT 'Telescope DECL',
  `ALT` float DEFAULT NULL COMMENT 'Telescope Altitude (deg) at exposure start',
  `AZ` float DEFAULT NULL COMMENT 'Telescope Azimuth (deg) at exposure start',
  `AIRMASS` float DEFAULT NULL COMMENT 'Telescope Airmass at exposure start',
  `CASANGLE` float DEFAULT NULL COMMENT 'Cassegrain angle of the P200',
  `SLITANGLE_REQ` varchar(8) DEFAULT NULL COMMENT 'Slit angle request',
  `POINTMODE` varchar(8) DEFAULT NULL COMMENT 'Where to place target (ACAM or SLIT)',
  `NOTBEFORE` datetime DEFAULT NULL COMMENT 'Earliest date/time to start exposure',
  `SLEW_START` datetime DEFAULT NULL COMMENT 'Slew start date/time',
  `SLEW_END` datetime DEFAULT NULL COMMENT 'Slew end date/time',
  `EXPTIME` float DEFAULT NULL COMMENT 'Exposure time (s)',
  `EXPTIME_REQ` varchar(12) DEFAULT NULL COMMENT 'Exposure time request',
  `EXP_START` datetime DEFAULT NULL COMMENT 'Exposure start date/time',
  `EXP_END` datetime DEFAULT NULL COMMENT 'Exposure end date/time',
  `SLITWIDTH` float DEFAULT NULL COMMENT 'Spectrograph slit width (arcsec)',
  `SLITWIDTH_REQ` varchar(12) DEFAULT NULL COMMENT 'Slit width request',
  `SLITOFFSET` float DEFAULT NULL COMMENT 'Slit lateral offset (arcsec)',
  `BINSPECT` int DEFAULT NULL COMMENT 'CCD binning in spectral direction',
  `BINSPAT` int DEFAULT NULL COMMENT 'CCD binning in spatial direction',
  `OBSMODE` varchar(32) DEFAULT NULL COMMENT 'Observation mode, CCD settings',
  `NOTE` varchar(512) DEFAULT NULL COMMENT 'Observer''s note on this target',
  `OTMFLAG` varchar(20) DEFAULT NULL COMMENT 'OTM flag codes at time of exposure',
  PRIMARY KEY (`LOG_ID`,`NAME`),
  UNIQUE KEY `LOG_ID_UNIQUE` (`LOG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
