CREATE TABLE `owner` (
  `OWNER_ID` varchar(64) NOT NULL,
  `PASSWORD` varchar(64) DEFAULT NULL,
  `EMAIL` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`OWNER_ID`),
  UNIQUE KEY `OWNER_ID_UNIQUE` (`OWNER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
