CREATE TABLE `target_sets` (
  `SET_ID` int NOT NULL AUTO_INCREMENT,
  `SET_NAME` varchar(64) NOT NULL,
  `OWNER` varchar(45) DEFAULT NULL,
  `STATE` varchar(16) DEFAULT NULL,
  `NUM_OBSERVATIONS` int DEFAULT NULL,
  `SET_CREATION_TIMESTAMP` timestamp(1) NOT NULL,
  `LAST_UPDATE_TIMESTAMP` timestamp(1) NULL DEFAULT NULL,
  PRIMARY KEY (`SET_ID`),
  UNIQUE KEY `set_id_UNIQUE` (`SET_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
