CREATE TABLE `targets_dev2` (
  `OBSERVATION_ID` int NOT NULL AUTO_INCREMENT,
  `SET_ID` int NOT NULL,
  `STATE` varchar(36) DEFAULT NULL,
  `OBS_ORDER` int NOT NULL,
  `TARGET_NUMBER` int NOT NULL,
  `SEQUENCE_NUMBER` int NOT NULL,
  `NAME` varchar(128) NOT NULL,
  `RA` varchar(32) DEFAULT NULL,
  `DECL` varchar(32) DEFAULT NULL,
  `OFFSET_RA` double DEFAULT NULL,
  `OFFSET_DEC` double DEFAULT NULL,
  `EXPTIME` varchar(32) NOT NULL,
  `SLITWIDTH` varchar(32) NOT NULL,
  `SLITOFFSET` double DEFAULT NULL,
  `OBSMODE` varchar(32) DEFAULT NULL,
  `BINSPECT` int DEFAULT NULL,
  `BINSPAT` int DEFAULT NULL,
  `SLITANGLE` varchar(32) DEFAULT NULL,
  `AIRMASS_MAX` varchar(32) DEFAULT NULL,
  `WRANGE_LOW` int DEFAULT NULL,
  `WRANGE_HIGH` int DEFAULT NULL,
  `CHANNEL` varchar(16) DEFAULT NULL,
  `MAGNITUDE` double DEFAULT NULL,
  `MAGSYSTEM` varchar(16) DEFAULT NULL,
  `MAGFILTER` varchar(16) DEFAULT NULL,
  `SRCMODEL` varchar(128) DEFAULT NULL,
  `OTMexpt` double DEFAULT NULL,
  `OTMslitwidth` double NOT NULL,
  `OTMcass` double DEFAULT NULL,
  `OTMairmass_start` double DEFAULT NULL,
  `OTMairmass_end` double DEFAULT NULL,
  `OTMsky` double DEFAULT NULL,
  `OTMdead` double DEFAULT NULL,
  `OTMslewgo` timestamp(1) NULL DEFAULT NULL,
  `OTMexp_start` timestamp(1) NULL DEFAULT NULL,
  `OTMexp_end` timestamp(1) NULL DEFAULT NULL,
  `OTMpa` double DEFAULT NULL,
  `OTMwait` double DEFAULT NULL,
  `OTMflag` varchar(32) DEFAULT NULL,
  `OTMlast` varchar(32) DEFAULT NULL,
  `OTMslew` double DEFAULT NULL,
  `OTMmoon` varchar(32) DEFAULT NULL,
  `OTMSNR` varchar(32) DEFAULT NULL,
  `OTMres` double DEFAULT NULL,
  `OTMseeing` double DEFAULT NULL,
  `OTMslitangle` double DEFAULT NULL,
  `NOTE` varchar(128) DEFAULT NULL,
  `COMMENT` varchar(1024) DEFAULT NULL,
  `OWNER` varchar(64) DEFAULT NULL,
  `NOTBEFORE` timestamp NULL DEFAULT NULL,
  `POINTMODE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`OBSERVATION_ID`,`OTMslitwidth`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
