#!/usr/bin/bash
#
# @file     acam
# @brief    provides a command line interface for acamd
#

source /home/developer/Software/run/ngps-config
source $ACAMD_CONFIG

command=""
while [ $# -gt 0 ]
do
    command="$command $1"
    shift 1
done
sock $NBPORT $command
