#!/usr/bin/bash
#
# @file     calib
# @brief    provides a command line interface for calibd
#

source $HOME/Software/Config/calibd.cfg

command=""
while [ $# -gt 0 ]
do
    command="$command $1"
    shift 1
done
sock $NBPORT $command
