#!/bin/bash
#
# @file     camera
# @brief    provides a command line interface for camerad
#

SCRIPT_DIR="$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"
source "${SCRIPT_DIR}/ngps-config"
source $CAMERAD_CONFIG

command=""
while [ $# -gt 0 ]
do
    command="$command $1"
    shift 1
done
sock $BLKPORT $command
