#!/bin/bash

# parse options
#
while [[ $# -gt 0 ]]; do
  case "$1" in
    -d|--date)
      DATE="$2"
      shift 2
      ;;
    -n|--name)
      NAME="$2"
      shift 2
      ;;
    *)
      echo "unrecognized option: $1"
      echo "usage: $0 [ --date YYYYMMDD ] [ --name <daemon> ]"
      exit 1
  esac
done

# if no date provided use the latest date found on disk
#
if [[ -z "$DATE" ]]; then
  DATA_ROOT="${NGPS_DATA_DIR:-/data}"
  DATE=$(ls -1 "$DATA_ROOT" 2>/dev/null | grep -E '^[0-9]{8}$' | sort -r | head -n 1)
fi

# log files are located in this directory
#
DATA_ROOT="${NGPS_DATA_DIR:-/data}"
DIR="${DATA_ROOT}/${DATE}/logs"

# these are all of the log files
# if no name provided then use all
#
if [[ -z "$NAME" ]]; then
  FILES="-f $DIR/acamd_$DATE.log \
         -f $DIR/slicecamd_$DATE.log \
         -f $DIR/calibd_$DATE.log \
         -f $DIR/camerad_$DATE.log \
         -f $DIR/flexured_$DATE.log \
         -f $DIR/focusd_$DATE.log \
         -f $DIR/powerd_$DATE.log \
         -f $DIR/slitd_$DATE.log \
         -f $DIR/tcsd_$DATE.log \
         -f $DIR/thermald_$DATE.log \
         -f $DIR/sequencerd_$DATE.log "
else
  FILES="-f "$DIR"/"$NAME"_"$DATE".log"
fi

# tail them all here
# look for various key words to set various colors
#
tail $FILES \
     | awk '{if ($3 ~ /ERROR/) print "\a\033[1;31m"$0"\033[0m"; \
             else if ($3 ~ /ERROR:/) print "\a\033[1;31m"$0"\033[0m"; \
             else if ($3 ~ /error/) print "\a\033[1;31m"$0"\033[0m"; \
             else if ($3 ~ /\[WARNING\]/) print "\a\033[1;31m"$0"\033[0m"; \
             else if ($3 ~ /POLLHUP/) print "\a\033[1;31m"$0"\033[0m"; \
             else if ($3 ~ /POLLERR/) print "\a\033[1;31m"$0"\033[0m"; \
             else if ($3 ~ /POLLNVAL/) print "\a\033[1;31m"$0"\033[0m"; \
             else if ($3 ~ /timeout/) print "\033[1;31m"$0"\033[0m"; \
             else if ($3 ~ /TIMEOUT/) print "\033[1;31m"$0"\033[0m"; \
             else if ($3 ~ /\[NOTICE\]/) print "\033[7;33m"$0"\033[0m"; \
             else if ($3 ~ /NOTICE/) print "\033[7;33m"$0"\033[0m"; \
             else if ($3 ~ /NOTICE:/) print "\033[7;33m"$0"\033[0m"; \
             else if ($3 ~ /TODO/) print "\033[7;33m"$0"\033[0m"; \
             else if ($3 ~ /\[TODO\]/) print "\033[7;33m"$0"\033[0m"; \
             else if ($3 ~ /\[DEBUG\]/) print "\033[7;36m"$0"\033[0m"; \
             else if ($3 ~ /seqstate/) print "\033[1;36m"$0"\033[0m"; \
             else if ($3 ~ /reqstate/) print "\033[1;36m"$0"\033[0m"; \
             else if ($3 ~ /threads/) print "\033[1;36m"$0"\033[0m"; \
             else print $0}'
