#!/usr/bin/bash
#
# @file     flexure
# @brief    provides a command line interface for flexured
#

source /home/developer/Software/run/ngps-config
source $FLEXURED_CONFIG

command=""
while [ $# -gt 0 ]
do
    command="$command $1"
    shift 1
done
sock $NBPORT $command
