#!/usr/bin/bash
#
# @file     listen
# @brief    provides a command line interface for sequencerd
#

source /home/developer/Software/run/ngps-config
source $SEQUENCERD_CONFIG

listener "$MESSAGEGROUP" "$MESSAGEPORT" "$@"
