#!/bin/bash
#
# @file     listen
# @brief    provides a command line interface for sequencerd
#

SCRIPT_DIR="$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"
source "${SCRIPT_DIR}/ngps-config"
source "$SEQUENCERD_CONFIG"

NGPS_ROOT="${NGPS_ROOT:-$(cd -- "${SCRIPT_DIR}/.." && pwd)}"
"${NGPS_ROOT}/bin/listener" "$MESSAGEGROUP" "$MESSAGEPORT" "$@"
