#!/bin/bash
#
# This script starts daemons, either the one specified by name, or all of them
#

# @fn:     usage
# @brief:  displays usage
# @param:  none
# @return: none
#
usage() {
	echo "Usage:"
	echo "	ngps start | stop | reload <module> [ <module> ... ]"
	echo "	ngps status"
	echo "	ngps list"
	echo ""
	exit
}

# @fn:     start_proc
# @brief:  runs a process as a daemon
# @param:  $1 = friendly name of process to start
# @param:  $2 = full path to process
# @param:  $3 = full path to process config file
# @return: 1 if process running, 0 if not
#
start_proc( ) {
	# Check if there are any existing processes with this name
	#
	fproc=$(eval "pgrep -f $2")
	nproc=$(eval "pgrep -c -f $2")
	if [ $nproc -gt 0 ]; then
		echo "$1 already running with PID $fproc"
		return 1
	fi

	# build and execute the command
	#
	cmd="$2 $3"$DAEMON
	echo "starting "$1"..."
	output=$(eval "$cmd")

	# wait 0.5 sec and check if the process is running
	#
	sleep 0.5
	running=$(eval "pgrep -c -f $2")
	if [ $running -lt 1 ]; then
		echo "error starting $1"
		return 0
	else
		echo "$1 running"
		return 1
	fi
}

# Get the fully qualified paths for each process and their config files here
#
source ~/Software/run/ngps-config

# Arrays of all processes, their associated names, and their associated config files
# These two arrays must be aligned!
#
#PROCS=("$CALIBD" "$CAMERAD" "$FLEXURED" "$FOCUSD" "$POWERD" "$SLITD" "$SEQUENCERD")
#PROCNAMES=("calibd" "camerad" "flexured" "focusd" "powerd" "slitd" "sequencerd")
#CONFIGS=("$CALIBD_CONFIG" "$CAMERAD_CONFIG" "$FLEXURED_CONFIG" "$FOCUSD_CONFIG" "$POWERD_CONFIG" "$SLITD_CONFIG" "$SEQUENCERD_CONFIG")

# Force daemon mode by default by adding " -d" to the command line
#
DAEMON=" -d"

if [ "$1" == "start" ]; then
	shift
	if [ $# == 0 ]; then
		usage
	fi

	for procname in "$@"
	do
		# Option to not pass the " -d" argument which forces daemon mode, but
		# can't guarantee that the config file doesn't override with DAEMON=yes
		#
		if [ "$procname" == "--no-daemon" ]; then
			DAEMON=""

		# For "start all" loop through all $PROCS and start each one.
		#
		elif [ "$procname" == "all" ]; then
			for i in "${!PROCS[@]}"; do
				start_proc ${PROCNAMES[$i]} ${PROCS[$i]} ${CONFIGS[$i]}
			done

		# Otherwise, search the $PROCNAMES array for the specified procname
		# and start only that one.
		#
		else
			namefound="false"

			for i in "${!PROCNAMES[@]}"; do
				if [ $procname == "${PROCNAMES[$i]}" ]; then
					start_proc ${PROCNAMES[$i]} ${PROCS[$i]} ${CONFIGS[$i]}
					namefound="true"
				fi
			done

			if [ "$namefound" == "false" ]; then
				echo "ERROR: unrecognized module: "$procname
			fi
		fi
	done

elif [ "$1" == "stop" ]; then
	shift
	for procname in "$@"
	do
		# For "stop all" loop through all $PROCS
		# If running then kill it.
		#
		if [ "$procname" == "all" ]; then
			for i in "${!PROCS[@]}"; do
				running=$(eval "pgrep -c -f ${PROCS[$i]}")
				if [ $running -gt 0 ]; then
					echo "killing "${PROCNAMES[$i]}
					$(eval "pkill -f ${PROCS[$i]}")
				fi
			done
			exit 0

		# Otherwise search all $PROCNAMES for the specified $procname
		# If running then kill only that one.
		#
		else
			namefound="false"

			for i in "${!PROCNAMES[@]}"; do
				if [ $procname == "${PROCNAMES[$i]}" ]; then
					running=$(eval "pgrep -c -f ${PROCS[$i]}")
					namefound="true"
					if [ $running -gt 0 ]; then
						echo "killing "$procname
						$(eval "pkill -f ${PROCS[$i]}")
					fi
				fi
			done

			if [ "$namefound" == "false" ]; then
				echo "ERROR: unrecognized module: "$procname
			fi
		fi

	done

elif [ "$1" == "status" ]; then
	shift
	for i in "${!PROCS[@]}"; do
		running=$(eval "pgrep -c -f ${PROCS[$i]}")
		procid=$(eval "pgrep -f ${PROCS[$i]}")
		if [ $running -gt 0 ]; then
			echo "  ${PROCNAMES[$i]} is running with pid $procid"
		else
			echo "* ${PROCNAMES[$i]} is not running"
		fi
	done

elif [ "$1" == "list" ]; then
	echo "recognized modules:"
	echo "	all"
	for name in "${PROCNAMES[@]}"; do
		echo "	$name"
	done
	exit
else
	usage
fi
