#!/usr/bin/bash
#
# @file     seq
# @brief    provides a command line interface for sequencerd
#

source /home/developer/Software/run/ngps-config
source $SEQUENCERD_CONFIG

command=""
while [ $# -gt 0 ]
do
    command="$command $1"
    shift 1
done
sock $NBPORT $command
