#!/bin/bash
#
# Launch the sequencer progress popup GUI
#

NGPS_ROOT=/home/developer/Software

CONFIG="${NGPS_ROOT}/Config/sequencerd.cfg"
exec "${NGPS_ROOT}/bin/seq_progress_gui" --config "${CONFIG}" --group NONE --msgport 0 --poll-ms 10000
