#!/usr/bin/bash
#
# @file     slit
# @brief    provides a command line interface for slitd
#

source $HOME/Software/Config/slitd.cfg

command=""
while [ $# -gt 0 ]
do
    command="$command $1"
    shift 1
done
sock $NBPORT $command
