#!/bin/bash
# name:   sock
# brief:  shell script to send commands to a server
# author: David Hale
#
# This script uses the sendsockcmd program to write commands to host:port
 
# The command is the first argument, then shift the next arg into first position
port=$1
shift 1
command=$1
shift 1

# build up string to send by adding each arg into command
while [ $# -gt 0 ]
do
	command="$command $1"
	shift 1
done

# send the command string
SCRIPT_DIR="$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"
NGPS_ROOT="${NGPS_ROOT:-$(cd -- "${SCRIPT_DIR}/.." && pwd)}"
HOST="${NGPS_HOST:-127.0.0.1}"
"${NGPS_ROOT}/bin/socksend" -h "$HOST" -p "$port" "$command" -t 5000
