#!/usr/bin/bash
#
# @file     telem
# @brief    provides a command line interface for telemd
#

source /home/developer/Software/run/ngps-config
source $TELEMD_CONFIG

command=""
while [ $# -gt 0 ]
do
    command="$command $1"
    shift 1
done
sock $NBPORT $command
