#!/usr/bin/bash
#
# @file     telem
# @brief    provides a command line interface for telemd
#

source $HOME/Software/Config/telemd.cfg

command=""
while [ $# -gt 0 ]
do
    command="$command $1"
    shift 1
done
sock $NBPORT $command
