#!/usr/bin/bash
#
# @file     thermal
# @brief    provides a command line interface for thermald
#

source /home/developer/Software/run/ngps-config
source $THERMALD_CONFIG

command=""
while [ $# -gt 0 ]
do
    command="$command $1"
    shift 1
done
sock $NBPORT $command
